version: '3.4'

services:
    gymmanagernet-sql:
        image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
        restart: unless-stopped
        environment:
            - ACCEPT_EULA=Y
            - SA_PASSWORD=reallyStrongPwd123
            - MSSQL_PID=Developer
        ports:
            - 1401:1433
        networks:
            - gymmanagernet

    GymManager3.webapi:
        restart: unless-stopped
        build:
            context: .
            dockerfile: GymManager3.WebAPI/Dockerfile
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - CONNECTION_STRING=Server=gymmanagernet-sql,1433;Database=GymManager1;User=sa;Password=reallyStrongPwd123;ConnectRetryCount=0
        ports:
            - 56230:80
        networks:
            - gymmanagernet      
        links:
            - gymmanagernet-sql
        depends_on:
            - gymmanagernet-sql

networks:
    gymmanagernet:
        driver: bridge